% import the labor input Total hours worked by persons engaged (millions)
cd '..\data'\wiod_sea\

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: data\WIOD_SEA_Feb12.xlsx
%    Worksheet: DATA
%
% Auto-generated by MATLAB on 03-Jul-2024 16:38:45

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 21);

% Specify sheet and range
opts.Sheet = "DATA";
opts.DataRange = "A2:U36001";

% Specify column names and types
opts.VariableNames = ["Country", "Variable", "Description", "Code", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["VarName20", "VarName21"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Country", "Variable", "Description", "Code", "VarName20", "VarName21"], "EmptyFieldRule", "auto");

% Import the data
WIODSEAFeb12S1 = readtable("WIOD_SEA_Feb12.xlsx", opts, "UseExcel", false);

% import labour input in working hours from WIOD SEA, the data for Rest of
% World is missing
wiod_l_index = WIODSEAFeb12S1.Variable == "H_EMP";
wiod_l_table = WIODSEAFeb12S1(wiod_l_index,:);
wiod_l_temp = double(table2array(wiod_l_table(:,5:17)));
wiod_l_row = zeros(36,13);
wiod_l = [wiod_l_temp; wiod_l_row];

% Clear temporary variables
clear opts

%% keep the needed industries and transform the data into 3 dimensions
l=zeros(30,13,41);
l_temp_t = transpose(wiod_l);
for j=1:41;
    l_firstpart = [l_temp_t(:,36*(j-1)+2:36*(j-1)+5) sum(l_temp_t(:,36*(j-1)+6:36*(j-1)+7),2) l_temp_t(:,36*(j-1)+8:36*(j-1)+24) sum(l_temp_t(:,36*(j-1)+25:36*(j-1)+28),2) l_temp_t(:,36*(j-1)+29:36*(j-1)+35)];
    l_temp_t_2=transpose(l_firstpart);
    l(:,:,j)=l_temp_t_2 ;
end

% clear the unnecessary data
clear wiod_l l_temp_t_2 l_temp_t l_firstpart j
